stages:
- build
- pages

fedora:
  stage: build
  image: registry.gitlab.gnome.org/gnome/gtk/fedora:v30
  script:
    - sudo dnf install -y vala sqlite-devel libsoup-devel gtk4-devel
    - meson _build -Db_coverage=true -Dgtk_doc=true
    - ninja -C _build shumate-doc
    - xvfb-run ninja -C _build test
    - ninja -C _build coverage
    - mv _build/docs/reference/html/ docs
    - mv _build/meson-logs/coveragereport coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  artifacts:
    paths:
    - docs
    - coverage

pages:
  stage: pages
  dependencies:
  - fedora
  script:
  - mv docs/html public
  - mv coverage public/
  artifacts:
    paths:
    - public
  only:
  - master

