stages:
- build
- pages

fedora:
  stage: build
  image: registry.gitlab.gnome.org/gnome/gtk/fedora:v38
  script:
    - sudo dnf install -y vala sqlite-devel libsoup3-devel gtk4-devel protobuf-c-devel gcovr
    - meson _build -Db_coverage=true -Dgtk_doc=true
    - xvfb-run ninja -C _build test
    - ninja -C _build coverage
    - mv _build/docs/libshumate-1.0 docs
    - mv _build/meson-logs/coveragereport coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  artifacts:
    paths:
    - docs
    - coverage
    reports:
      coverage_report:
        coverage_format: cobertura
        path: _build/meson-logs/coverage.xml


pages:
  stage: pages
  dependencies:
  - fedora
  script:
  - mv docs/libshumate-1.0 public
  - mv coverage public/
  artifacts:
    paths:
    - public
  only:
  - main

